import { XFramesStyleForPatching, ImGuiCol } from "@xframes/common";

export const themeColors = {
  deepNavy: "#1a1b2e",
  navy: "#252641",
  midNavy: "#2f3055",
  slate: "#4a4b6a",
  lightSlate: "#7a7b9a",
  silver: "#b8bbd0",
  offWhite: "#e8eaf6",
  teal: "#56d6d6",
  hoverTeal: "#7aeaea",
};

export const theme: XFramesStyleForPatching = {
  colors: {
    [ImGuiCol.Text]: [themeColors.offWhite, 1],
    [ImGuiCol.TextDisabled]: [themeColors.lightSlate, 1],
    [ImGuiCol.WindowBg]: [themeColors.deepNavy, 1],
    [ImGuiCol.ChildBg]: [themeColors.deepNavy, 1],
    [ImGuiCol.PopupBg]: [themeColors.navy, 1],
    [ImGuiCol.Border]: [themeColors.slate, 1],
    [ImGuiCol.BorderShadow]: [themeColors.deepNavy, 1],
    [ImGuiCol.FrameBg]: [themeColors.navy, 1],
    [ImGuiCol.FrameBgHovered]: [themeColors.midNavy, 1],
    [ImGuiCol.FrameBgActive]: [themeColors.slate, 1],
    [ImGuiCol.TitleBg]: [themeColors.navy, 1],
    [ImGuiCol.TitleBgActive]: [themeColors.midNavy, 1],
    [ImGuiCol.TitleBgCollapsed]: [themeColors.navy, 1],
    [ImGuiCol.MenuBarBg]: [themeColors.navy, 1],
    [ImGuiCol.ScrollbarBg]: [themeColors.deepNavy, 1],
    [ImGuiCol.ScrollbarGrab]: [themeColors.slate, 1],
    [ImGuiCol.ScrollbarGrabHovered]: [themeColors.lightSlate, 1],
    [ImGuiCol.ScrollbarGrabActive]: [themeColors.silver, 1],
    [ImGuiCol.CheckMark]: [themeColors.teal, 1],
    [ImGuiCol.SliderGrab]: [themeColors.teal, 1],
    [ImGuiCol.SliderGrabActive]: [themeColors.hoverTeal, 1],
    [ImGuiCol.Button]: [themeColors.midNavy, 1],
    [ImGuiCol.ButtonHovered]: [themeColors.slate, 1],
    [ImGuiCol.ButtonActive]: [themeColors.teal, 1],
    [ImGuiCol.Header]: [themeColors.midNavy, 1],
    [ImGuiCol.HeaderHovered]: [themeColors.slate, 1],
    [ImGuiCol.HeaderActive]: [themeColors.teal, 1],
    [ImGuiCol.Separator]: [themeColors.slate, 1],
    [ImGuiCol.SeparatorHovered]: [themeColors.lightSlate, 1],
    [ImGuiCol.SeparatorActive]: [themeColors.teal, 1],
    [ImGuiCol.ResizeGrip]: [themeColors.midNavy, 1],
    [ImGuiCol.ResizeGripHovered]: [themeColors.slate, 1],
    [ImGuiCol.ResizeGripActive]: [themeColors.teal, 1],
    [ImGuiCol.Tab]: [themeColors.navy, 1],
    [ImGuiCol.TabHovered]: [themeColors.midNavy, 1],
    [ImGuiCol.TabActive]: [themeColors.teal, 1],
    [ImGuiCol.TabUnfocused]: [themeColors.navy, 1],
    [ImGuiCol.TabUnfocusedActive]: [themeColors.slate, 1],
    [ImGuiCol.PlotLines]: [themeColors.teal, 1],
    [ImGuiCol.PlotLinesHovered]: [themeColors.hoverTeal, 1],
    [ImGuiCol.PlotHistogram]: [themeColors.teal, 1],
    [ImGuiCol.PlotHistogramHovered]: [themeColors.hoverTeal, 1],
    [ImGuiCol.TableHeaderBg]: [themeColors.navy, 1],
    [ImGuiCol.TableBorderStrong]: [themeColors.slate, 1],
    [ImGuiCol.TableBorderLight]: [themeColors.midNavy, 1],
    [ImGuiCol.TableRowBg]: [themeColors.deepNavy, 1],
    [ImGuiCol.TableRowBgAlt]: [themeColors.navy, 1],
    [ImGuiCol.TextSelectedBg]: [themeColors.slate, 1],
    [ImGuiCol.DragDropTarget]: [themeColors.teal, 1],
    [ImGuiCol.NavHighlight]: [themeColors.teal, 1],
    [ImGuiCol.NavWindowingHighlight]: [themeColors.teal, 1],
    [ImGuiCol.NavWindowingDimBg]: [themeColors.deepNavy, 1],
    [ImGuiCol.ModalWindowDimBg]: [themeColors.deepNavy, 1],
  },
};
